name: Deploy Pipeline to Ubuntu Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🚀 Deploy to Production Folders
        run: |
          echo "Setting up pipeline directory..."
          mkdir -p /home/vagrant/data_pipeline
          
          echo "Copying Python extractor..."
          cp extract_weather.py /home/vagrant/data_pipeline/
          
          echo "Copying requirements..."
          cp requirements.txt /home/vagrant/data_pipeline/
